version: 2

builds:
  - binary: markdocs
    ldflags:
      - -X 'github.com/Nithin-Valiyaveedu/markdocs/cmd.Version=v{{ .Version }}'
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "markdocs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
