builds:
  - binary: markdocs
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "markdocs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

homebrew_casks:
  - name: markdocs
    repository:
      owner: Nithin-Valiyaveedu
      name: homebrew-markdocs
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    binaries:
      - markdocs
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/markdocs"]
          end
